### ISSUE TITLE
Issue while compiling code in XCode 12.3

### ISSUE THREAD

**Issue by ThangaAyyanar** [nkbelov/ListView#1]
- Issue: Variable used within its own initial value
- In ListView, Line number: 120
```
let type = type(of: view)
```
- The issue is due to two **type** - one is variable and other one is function
- Changing the variable name fixed the issue.
- Just thought of let you know.

**Comment by nkbelov** [comment]
Oh, curious, my Xcode 12.5 didn't complain about this. I have updated the variable's name.
